package spitapp.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;

public class DocumentGuiHandler extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_dokument;
	@AutoGenerated
	private Button button_dokumente;
	@AutoGenerated
	private ComboBox comboBox_Dokumente;
	@AutoGenerated
	private Label data_hobbies;
	@AutoGenerated
	private Label label_hobbies;
	@AutoGenerated
	private Label data_pflegestufe;
	@AutoGenerated
	private Label label_pflegestufe;
	@AutoGenerated
	private Label data_alter;
	@AutoGenerated
	private Label label_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DocumentGuiHandler() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		comboBox_Dokumente.addItem("Patienteninfo.pdf");
		comboBox_Dokumente.addItem("Krankheit xy.pdf");
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_1
		label_1 = new Label();
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Alter:");
		mainLayout.addComponent(label_1, "top:24.0px;left:20.0px;");
		
		// data_alter
		data_alter = new Label();
		data_alter.setImmediate(false);
		data_alter.setWidth("90px");
		data_alter.setHeight("-1px");
		data_alter.setValue("84");
		mainLayout.addComponent(data_alter, "top:24.0px;left:110.0px;");
		
		// label_pflegestufe
		label_pflegestufe = new Label();
		label_pflegestufe.setImmediate(false);
		label_pflegestufe.setWidth("-1px");
		label_pflegestufe.setHeight("-1px");
		label_pflegestufe.setValue("Pflegestufe:");
		mainLayout.addComponent(label_pflegestufe, "top:60.0px;left:20.0px;");
		
		// data_pflegestufe
		data_pflegestufe = new Label();
		data_pflegestufe.setImmediate(false);
		data_pflegestufe.setWidth("110px");
		data_pflegestufe.setHeight("-1px");
		data_pflegestufe.setValue("8b");
		mainLayout.addComponent(data_pflegestufe, "top:60.0px;left:110.0px;");
		
		// label_hobbies
		label_hobbies = new Label();
		label_hobbies.setImmediate(false);
		label_hobbies.setWidth("-1px");
		label_hobbies.setHeight("-1px");
		label_hobbies.setValue("Hobbies:");
		mainLayout.addComponent(label_hobbies, "top:100.0px;left:20.0px;");
		
		// data_hobbies
		data_hobbies = new Label();
		data_hobbies.setImmediate(false);
		data_hobbies.setWidth("100.0%");
		data_hobbies.setHeight("40px");
		data_hobbies.setValue("Jassen, Essen");
		mainLayout.addComponent(data_hobbies, "top:120.0px;left:20.0px;");
		
		// comboBox_Dokumente
		comboBox_Dokumente = new ComboBox();
		comboBox_Dokumente.setImmediate(false);
		comboBox_Dokumente.setWidth("-1px");
		comboBox_Dokumente.setHeight("-1px");
		comboBox_Dokumente.setInvalidAllowed(false);
		mainLayout.addComponent(comboBox_Dokumente, "top:200.0px;left:22.0px;");
		
		// button_dokumente
		button_dokumente = new Button();
		button_dokumente.setCaption("Öffnen");
		button_dokumente.setImmediate(true);
		button_dokumente.setWidth("-1px");
		button_dokumente.setHeight("-1px");
		mainLayout.addComponent(button_dokumente, "top:198.0px;left:214.0px;");
		
		// label_dokument
		label_dokument = new Label();
		label_dokument.setImmediate(false);
		label_dokument.setWidth("-1px");
		label_dokument.setHeight("-1px");
		label_dokument.setValue("Verfügbare Partienten-Dokumente:");
		mainLayout.addComponent(label_dokument, "top:180.0px;left:22.0px;");
		
		return mainLayout;
	}

}
