package spitapp.gui;

import spitapp.controller.AppointmentChangedEvent;
import spitapp.controller.AppointmentController;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;

@SuppressWarnings("serial")
public class DocumentGuiHandler extends DetailGuiHandler {

	// the gui components
	private AbsoluteLayout mainLayout;
	private Label age;
	private Label ageData;
	private Label careLevel;
	private Label careLevelData;
	private Label hobbies;
	private Label hobbiesData;
	private Label lblDocument;
	private Button btnDocument;
	private ComboBox cbxDocuments;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public DocumentGuiHandler(AppointmentController controller) {
		super(controller);
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		cbxDocuments.addItem("Patienteninfo.pdf");
		cbxDocuments.addItem("Krankheit xy.pdf");
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// label_1
		age = new Label();
		age.setImmediate(false);
		age.setWidth("-1px");
		age.setHeight("-1px");
		age.setValue("Alter:");
		mainLayout.addComponent(age, "top:24.0px;left:20.0px;");
		
		// data_alter
		ageData = new Label();
		ageData.setImmediate(false);
		ageData.setWidth("90px");
		ageData.setHeight("-1px");
		ageData.setValue("84");
		mainLayout.addComponent(ageData, "top:24.0px;left:110.0px;");
		
		// label_pflegestufe
		careLevel = new Label();
		careLevel.setImmediate(false);
		careLevel.setWidth("-1px");
		careLevel.setHeight("-1px");
		careLevel.setValue("Pflegestufe:");
		mainLayout.addComponent(careLevel, "top:60.0px;left:20.0px;");
		
		// data_pflegestufe
		careLevelData = new Label();
		careLevelData.setImmediate(false);
		careLevelData.setWidth("110px");
		careLevelData.setHeight("-1px");
		careLevelData.setValue("8b");
		mainLayout.addComponent(careLevelData, "top:60.0px;left:110.0px;");
		
		// label_hobbies
		hobbies = new Label();
		hobbies.setImmediate(false);
		hobbies.setWidth("-1px");
		hobbies.setHeight("-1px");
		hobbies.setValue("Hobbies:");
		mainLayout.addComponent(hobbies, "top:100.0px;left:20.0px;");
		
		// data_hobbies
		hobbiesData = new Label();
		hobbiesData.setImmediate(false);
		hobbiesData.setWidth("100.0%");
		hobbiesData.setHeight("40px");
		hobbiesData.setValue("Jassen, Essen");
		mainLayout.addComponent(hobbiesData, "top:120.0px;left:20.0px;");
		
		// comboBox_Dokumente
		cbxDocuments = new ComboBox();
		cbxDocuments.setImmediate(false);
		cbxDocuments.setWidth("-1px");
		cbxDocuments.setHeight("-1px");
		cbxDocuments.setInvalidAllowed(false);
		mainLayout.addComponent(cbxDocuments, "top:200.0px;left:22.0px;");
		
		// button_dokumente
		btnDocument = new Button();
		btnDocument.setCaption("Öffnen");
		btnDocument.setImmediate(true);
		btnDocument.setWidth("-1px");
		btnDocument.setHeight("-1px");
		mainLayout.addComponent(btnDocument, "top:198.0px;left:214.0px;");
		
		// label_dokument
		lblDocument = new Label();
		lblDocument.setImmediate(false);
		lblDocument.setWidth("-1px");
		lblDocument.setHeight("-1px");
		lblDocument.setValue("Verfügbare Partienten-Dokumente:");
		mainLayout.addComponent(lblDocument, "top:180.0px;left:22.0px;");
		
		return mainLayout;
	}

	@Override
	public void handleAppointmentChangedEvent(AppointmentChangedEvent e) {
		// TODO Auto-generated method stub
		AppointmentController ctrl = (AppointmentController)e.getSource();
		
		ageData.setData(ctrl.getCurrentAppointment().getPatient().getFirstName());
	}

}
