package spitapp.gui;

import spitapp.controller.AppointmentChangedEvent;
import spitapp.controller.AppointmentController;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.Table;

@SuppressWarnings("serial")
public class ExpensesGuiHandler extends DetailGuiHandler {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Label label_neu;
	@AutoGenerated
	private Label label_waehrung;
	@AutoGenerated
	private Button button_add;
	@AutoGenerated
	private ComboBox comboBox_betrag;
	@AutoGenerated
	private ComboBox comboBox_spesenart;
	@AutoGenerated
	private Table table_spesen;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ExpensesGuiHandler(AppointmentController controller) {
		super(controller);
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table_1
		table_spesen = new Table();
		table_spesen.setImmediate(false);
		table_spesen.setWidth("100.0%");
		table_spesen.setHeight("303px");
		mainLayout.addComponent(table_spesen, "top:17.0px;right:58.0px;left:0.0px;");
		
		// comboBox_spesenart
		comboBox_spesenart = new ComboBox();
		comboBox_spesenart.setImmediate(false);
		comboBox_spesenart.setWidth("240px");
		comboBox_spesenart.setHeight("-1px");
		mainLayout.addComponent(comboBox_spesenart, "top:356.0px;left:0.0px;");
		
		// comboBox_betrag
		comboBox_betrag = new ComboBox();
		comboBox_betrag.setImmediate(false);
		comboBox_betrag.setWidth("80px");
		comboBox_betrag.setHeight("-1px");
		mainLayout.addComponent(comboBox_betrag, "top:356.0px;left:260.0px;");
		
		// button_add
		button_add = new Button();
		button_add.setCaption("+");
		button_add.setImmediate(false);
		button_add.setWidth("-1px");
		button_add.setHeight("-1px");
		mainLayout.addComponent(button_add, "top:356.0px;left:420.0px;");
		
		// label_waehrung
		label_waehrung = new Label();
		label_waehrung.setImmediate(false);
		label_waehrung.setWidth("-1px");
		label_waehrung.setHeight("-1px");
		label_waehrung.setValue("CHF");
		mainLayout.addComponent(label_waehrung, "top:362.0px;left:355.0px;");
		
		// label_1
		label_neu = new Label();
		label_neu.setImmediate(false);
		label_neu.setWidth("-1px");
		label_neu.setHeight("-1px");
		label_neu.setValue("Label");
		mainLayout.addComponent(label_neu, "top:340.0px;left:9.0px;");
		
		return mainLayout;
	}

	@Override
	public void handleAppointmentChangedEvent(AppointmentChangedEvent e) {
		// TODO Auto-generated method stub
		
	}

}
