package spitapp.gui;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Table;
import com.vaadin.ui.UI;
import com.vaadin.ui.Window;



public class TerminEintragGuiHandler extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private AbsoluteLayout mainLayout;
	@AutoGenerated
	private Button button_vorwaerts;
	@AutoGenerated
	private Button button_datum;
	@AutoGenerated
	private Button button_rueckwaerts;
	@AutoGenerated
	private Table table_termine;

	Window window_date; //The window with the date

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TerminEintragGuiHandler() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here	
	}


	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// table_termine
		table_termine = new Table();
		table_termine.setImmediate(false);
		table_termine.setWidth("100.0%");
		table_termine.setHeight("-1px");
		mainLayout.addComponent(table_termine, "top:17.0px;left:20.0px;");
		
		// button_rueckwaerts
		button_rueckwaerts = new Button();
		button_rueckwaerts.setCaption("Rückwärts");
		button_rueckwaerts.setImmediate(true);
		button_rueckwaerts.setWidth("-1px");
		button_rueckwaerts.setHeight("-1px");
		button_rueckwaerts.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				//Code
			}
	    });
		mainLayout.addComponent(button_rueckwaerts, "top:348.0px;left:20.0px;");
		
		// button_datum
		button_datum = new Button();
		button_datum.setCaption("Datum");
		button_datum.setImmediate(true);
		button_datum.setWidth("-1px");
		button_datum.setHeight("-1px");
		button_datum.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				 /* Create a new window. */
		        window_date = new Window("Datum auswählen");
		        window_date.setPositionX(200);
		        window_date.setPositionY(100);
		        /* Add the window inside the main window. */
		        UI.getCurrent().addWindow(window_date);
			}
	    });
		mainLayout.addComponent(button_datum, "top:348.0px;left:106.0px;");
		
		// button_vorwaerts
		button_vorwaerts = new Button();
		button_vorwaerts.setCaption("Vorwärts");
		button_vorwaerts.setImmediate(true);
		button_vorwaerts.setWidth("-1px");
		button_vorwaerts.setHeight("-1px");
		button_vorwaerts.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				//Code
			}
	    });
		mainLayout.addComponent(button_vorwaerts, "top:348.0px;left:171.0px;");
		
		return mainLayout;
	}
}
