package spitapp.gui;

import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.HashMap;

import spitapp.core.model.TerminEintrag;
import spitapp.core.service.DatabaseService;

import com.vaadin.data.Property.ValueChangeEvent;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.data.Property.ValueChangeListener;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.Table;
import com.vaadin.ui.VerticalLayout;

public class TerminEintragGuiHandler extends CustomComponent {

	private AbsoluteLayout mainLayout;
	private Button buttonForward;
	private PopupDateField dateFieldDate;
	private Button buttonBackward;
	private Table tableAppointments;
	
	public HashMap<Integer, TerminEintrag> eintraege = new HashMap<Integer, TerminEintrag>();
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public TerminEintragGuiHandler() {

		buildMainLayout();
		setCompositionRoot(mainLayout);

		// initialize with actual date
		DateChanged(dateFieldDate.getValue());
	}
	
	public void TerminEintragChanged(Integer newTerminId) {
		tableAppointments.setCaption("Selected: " + tableAppointments.getValue());	
	}
	
	public boolean clearTermine() {
		if(tableAppointments.removeAllItems()) {
			this.eintraege.clear();
			return true;
		}
		return false;
	}
	
	public boolean addTermin(TerminEintrag termin) {
		Integer pos = (Integer)tableAppointments.addItem(new Object[] { termin.getPatient().getFirstName() + " " + termin.getPatient().getLastName(), termin.getTerminDate().toString() }, null);
		if( pos != null) {
			this.eintraege.put(pos, termin);
			return true;
		}
		return false;
	}
	
	public void DateChanged(Date newDate) {
		clearTermine();
		
		DatabaseService dbservice = new DatabaseService();
		List<TerminEintrag> termine = dbservice.getTermine(newDate);
		
		for (TerminEintrag termin: termine) {
			this.addTermin(termin);
		}
		
	}

	@AutoGenerated
	private AbsoluteLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new AbsoluteLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		//layout for TerminEintrag section
		VerticalLayout terminLayout = new VerticalLayout();
		terminLayout.setMargin(true);
		
		//layout for the buttons forward, date, backward
		HorizontalLayout buttonLayout = new HorizontalLayout();

		// table_termine
		tableAppointments = new Table("Termine");
		tableAppointments.setImmediate(false);
		tableAppointments.setWidth("100.0%");
		tableAppointments.setHeight("-1px");
		/* Define the names and data types of columns.
		 * The "default value" parameter is meaningless here. */
		tableAppointments.addContainerProperty("Patient", String.class,  null);
		tableAppointments.addContainerProperty("Uhrzeit",  String.class,  null);
		// Allow selecting items from the table.
		tableAppointments.setSelectable(true);
		// Send changes in selection immediately to server.
		tableAppointments.setImmediate(true);
		// Handle selection change.
		tableAppointments.addValueChangeListener(new ValueChangeListener() {
		    public void valueChange(ValueChangeEvent event) {
		    	TerminEintragChanged((Integer)tableAppointments.getValue());
		        
		    }
		});
		
		// button_rueckwaerts
		buttonBackward = new Button();
		buttonBackward.setCaption("Rückwärts");
		buttonBackward.setImmediate(true);
		buttonBackward.setWidth("-1px");
		buttonBackward.setHeight("-1px");
		buttonBackward.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				Calendar calendar = new GregorianCalendar();
				calendar.setTime(dateFieldDate.getValue());
				calendar.add(Calendar.DAY_OF_MONTH, -1);
				dateFieldDate.setValue(calendar.getTime());
			}
		}); 	
		
		// dateField_datum
		dateFieldDate = new PopupDateField();
		dateFieldDate.setImmediate(true);
		dateFieldDate.setWidth("-1px");
		dateFieldDate.setHeight("-1px");
		dateFieldDate.setDateFormat("dd-MM-yyyy");
		dateFieldDate.setValue(new Date());
		dateFieldDate.addValueChangeListener(new ValueChangeListener() {
		    public void valueChange(ValueChangeEvent event) {
		        DateChanged(dateFieldDate.getValue());
		    }
		});
		
		// buttonForward
		buttonForward = new Button();
		buttonForward.setCaption("Vorwärts");
		buttonForward.setImmediate(true);
		buttonForward.setWidth("-1px");
		buttonForward.setHeight("-1px");
		buttonForward.addClickListener(new Button.ClickListener() {
			public void buttonClick(ClickEvent event) {
				Calendar calendar = new GregorianCalendar();
				calendar.setTime(dateFieldDate.getValue());
				calendar.add(Calendar.DAY_OF_MONTH, 1);
				dateFieldDate.setValue(calendar.getTime());
			}
		}); 		
		
		//Set the layout together
		buttonLayout.addComponent(buttonBackward);
		buttonLayout.addComponent(dateFieldDate);
		buttonLayout.addComponent(buttonForward);
		terminLayout.addComponent(tableAppointments);
		terminLayout.addComponent(buttonLayout);
		mainLayout.addComponent(terminLayout);
		return mainLayout;
	}
}
